### ISSUE TITLE
Beschreibung für Benutzer des Programms aus #10

### ISSUE THREAD

**Issue by DenisBrendel** [DenisBrendel/Informatik-Projekt#11]
Hier müssen wir die README.md Datei ändern und eine kleine Beschreibung für Nutzer unseres Programms zu schreiben

**Comment by nicolaiparlog** [comment]
@FrEeDoM-Sc2 Warum hast du das Issue geschlossen? In der README finde ich die Anleitung nicht, oder habe ich sie übersehen?

**Comment by FrEeDoM-Sc2** [comment]
Sollte drin sein. Ganz unten. Kann die aber auch nach vorne ziehen.


Von meinem Samsung Gerät gesendet.

-------- Ursprüngliche Nachricht --------
Von: Nicolai Parlog <notifications@github.com> 
Datum: 04.08.17  14:31  (GMT+01:00) 
An: DenisBrendel/Informatik-Projekt <Informatik-Projekt@noreply.github.com> 
Cc: FrEeDoM-Sc2 <m.maison.sc2@gmx.de>, Mention <mention@noreply.github.com> 
Betreff: Re: [DenisBrendel/Informatik-Projekt] Beschreibung für Benutzer des Programms aus #10 (#11) 

@FrEeDoM-Sc2 Warum hast du das Issue geschlossen? In der README finde ich die Anleitung nicht, oder habe ich sie übersehen?

—
You are receiving this because you were mentioned.
Reply to this email directly, view it on GitHub, or mute the thread.


  
  




{"api_version":"1.0","publisher":{"api_key":"05dde50f1d1a384dd78767c55493e4bb","name":"GitHub"},"entity":{"external_key":"github/DenisBrendel/Informatik-Projekt","title":"DenisBrendel/Informatik-Projekt","subtitle":"GitHub repository","main_image_url":"https://cloud.githubusercontent.com/assets/143418/17495839/a5054eac-5d88-11e6-95fc-7290892c7bb5.png","avatar_image_url":"https://cloud.githubusercontent.com/assets/143418/15842166/7c72db34-2c0b-11e6-9aed-b52498112777.png","action":{"name":"Open in GitHub","url":"https://github.com/DenisBrendel/Informatik-Projekt"}},"updates":{"snippets":[{"icon":"PERSON","message":"@nicolaiparlog in #11: @FrEeDoM-Sc2 Warum hast du das Issue geschlossen? In der README finde ich die Anleitung nicht, oder habe ich sie übersehen?"}],"action":{"name":"View Issue","url":"https://github.com/DenisBrendel/Informatik-Projekt/issues/11#issuecomment-320236760"}}}

**Comment by nicolaiparlog** [comment]
Stimmt. Ja weiter oben wäre gut. Muss aber nicht jetzt gemacht werden - irgendwann wird die README ja wieder angepasst.

**Comment by FrEeDoM-Sc2** [comment]
Und wie ist das dann mit dem taggen? Ich hätte wohl einen annotated tag gemacht.


Von meinem Samsung Gerät gesendet.

-------- Ursprüngliche Nachricht --------
Von: Nicolai Parlog <notifications@github.com> 
Datum: 04.08.17  15:26  (GMT+01:00) 
An: DenisBrendel/Informatik-Projekt <Informatik-Projekt@noreply.github.com> 
Cc: FrEeDoM-Sc2 <m.maison.sc2@gmx.de>, Mention <mention@noreply.github.com> 
Betreff: Re: [DenisBrendel/Informatik-Projekt] Beschreibung für Benutzer des Programms aus #10 (#11) 

Stimmt. Ja weiter oben wäre gut. Muss aber nicht jetzt gemacht werden - irgendwann wird die README ja wieder angepasst.

—
You are receiving this because you were mentioned.
Reply to this email directly, view it on GitHub, or mute the thread.


  
  




{"api_version":"1.0","publisher":{"api_key":"05dde50f1d1a384dd78767c55493e4bb","name":"GitHub"},"entity":{"external_key":"github/DenisBrendel/Informatik-Projekt","title":"DenisBrendel/Informatik-Projekt","subtitle":"GitHub repository","main_image_url":"https://cloud.githubusercontent.com/assets/143418/17495839/a5054eac-5d88-11e6-95fc-7290892c7bb5.png","avatar_image_url":"https://cloud.githubusercontent.com/assets/143418/15842166/7c72db34-2c0b-11e6-9aed-b52498112777.png","action":{"name":"Open in GitHub","url":"https://github.com/DenisBrendel/Informatik-Projekt"}},"updates":{"snippets":[{"icon":"PERSON","message":"@nicolaiparlog in #11: Stimmt. Ja weiter oben wäre gut. Muss aber nicht jetzt gemacht werden - irgendwann wird die README ja wieder angepasst. "}],"action":{"name":"View Issue","url":"https://github.com/DenisBrendel/Informatik-Projekt/issues/11#issuecomment-320248382"}}}

**Comment by nicolaiparlog** [comment]
Gehört der Kommentar an ein anderes Ticket oder sehe ich den Zusammenhang nur nicht?
